name: Bahamut Anime Count Test
on:
  #  schedule:
  #    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      id:
        description: "ID"
        required: false
        default: "15357"
      count:
        description: "次數"
        required: false
        default: "100"
jobs:
  add:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Packages
        run: npm install
      - name: Test
        run: node index.js ${{ github.event.inputs.id }} ${{ github.event.inputs.count }}
